In [1]:
import numpy as np

In [2]:
import sys
!{sys.executable} -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

In [4]:
arr = np.array([1,3,6,8,9])
print(arr)

[1 3 6 8 9]


In [5]:
print(np.__version__)

1.19.2


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr = np.array({'key':'val'})

In [8]:
print(arr)

{'key': 'val'}


# 0-D array

In [9]:
arr = np.array(12)

In [10]:
print(arr)

12


# 01-D array

In [11]:
arr = np.array([12])
print(arr)

[12]


# 2-D array

In [12]:
arr = np.array([[12,5,8], [1,5,8]])
print(arr)

[[12  5  8]
 [ 1  5  8]]


In [13]:
arr = np.array([12,5,88,8.5,5*6])
print(arr)

[12.   5.  88.   8.5 30. ]


In [14]:
import sys
!{sys.executable} -m pip install numpy --upgrade

Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: numpy in /home/maaz/.local/lib/python3.8/site-packages (1.19.2)


In [15]:
arr = np.array([[12,5,8], [1,5,8]])
print(arr)

[[12  5  8]
 [ 1  5  8]]


In [16]:
a = np.array([[[12,5,8], [1,5,8]],[[12,5,8], [1,5,8]]])
b = np.array(-5)
c = np.array([66,97])
d = np.array([[45,8,99,5],[88,77,22,99]])
print(a.ndim)
print('a :' ,a)
print(b.ndim)
print('b :' ,b)
print(c.ndim)
print('c :' ,c)
print(d.ndim)
print('d :' ,d)

3
a : [[[12  5  8]
  [ 1  5  8]]

 [[12  5  8]
  [ 1  5  8]]]
0
b : -5
1
c : [66 97]
2
d : [[45  8 99  5]
 [88 77 22 99]]


## Check Number of Dimensions

In [17]:
a = np.array([[[12,5,8], [1,5,8]],[[12,5,8], [1,5,8]]])
b = np.array(-5)
c = np.array([66,97])
d = np.array([[45,8,99,5],[88,77,22,99]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

3
0
1
2


## Higher Dimensional Arrays Using ndmin = no. of D or minimum dimensions 

In [18]:
a = np.array([55,88,99,66], ndmin = 5) #defining number of D
b = np.array([8,55,98,4,22,6],[5,8,5,6,9], ndmin =5)

print(a.ndim)
print(b.ndim)


TypeError: Field elements must be 2- or 3-tuples, got '5'

In [ ]:
a = np.array([55,88,99,66], ndmin = 5) #defining number of D
b = np.array([[8,55,98,4,22],[5,8,5,6,9]], ndmin =3)

print(a.ndim)
print(b.ndim)

#printing array
print(a)
print()
print(b)

## In this array the
    innermost dimension (5th dim) has 4 elements, 
    the 4th dim has 1 element that is the vector, the 
    3rd dim has 1 element that is the matrix with the vector, 
    the 2nd dim has 1 element that is 3D array and 
    1st dim has 1 element that is a 4D array.

In [ ]:
#multiple dimentions with dtype


In [ ]:
a = np.array([[23,98,88],[77,88,99]], ndmin = 2 ,dtype = int)
print(a)
print(a.ndim)

a.shape = (3,2)
print(a.shape)
print(a)

## Indexing

In [ ]:
a = np.array([4,45,5,6,7]) 
print(a[4]) #accessing 1-D array
print(a[2], a[3])
print(a[2]+a[3])
a


In [ ]:
a = np.array([[[1,2,3,4,5], [6,7,8,9,10]],
              [[11,12,13,14,15],[16,17,18,19,20]]])
print('shape :',a.shape)
print('dimentions: ',a.ndim)
print('A 2 x 5: ',a[0,0,1])


print('array 1:')
a

# Accessing indexes

In [ ]:
a=np.array([1,2,3,4,5])
a

In [8]:
a=np.array([1,2,3,4,5])
a[0],a[3],a[1]

(1, 4, 2)

In [39]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

r = 0
c = 0
# i = 0
for i in range(6):
#     print(i)
    print(f'A {r} x {c} :',a[r,c]) 
    
    c += 1
    
    if i == 2 :
        r += 1
        c = 0
        
    

A 0 x 0 : 1
A 0 x 1 : 2
A 0 x 2 : 3
A 1 x 0 : 6
A 1 x 1 : 7
A 1 x 2 : 8


In [43]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
             [[11,12,13,14,15],[16,17,18,19,20]]])


3

In [50]:
a =np.arange(101,300,2)

In [51]:
a

array([101, 103, 105, 107, 109, 111, 113, 115, 117, 119, 121, 123, 125,
       127, 129, 131, 133, 135, 137, 139, 141, 143, 145, 147, 149, 151,
       153, 155, 157, 159, 161, 163, 165, 167, 169, 171, 173, 175, 177,
       179, 181, 183, 185, 187, 189, 191, 193, 195, 197, 199, 201, 203,
       205, 207, 209, 211, 213, 215, 217, 219, 221, 223, 225, 227, 229,
       231, 233, 235, 237, 239, 241, 243, 245, 247, 249, 251, 253, 255,
       257, 259, 261, 263, 265, 267, 269, 271, 273, 275, 277, 279, 281,
       283, 285, 287, 289, 291, 293, 295, 297, 299])

In [8]:
a=a.reshape(10,2,5)

In [9]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [20]:
a[9][0][4] # 10th array, 1st vect, 5th element = 94

94

In [19]:
a[[9],[0],[4]] # 10th array, 1st vect, 5th element = 94

array([94])

In [63]:
a=a.reshape(1,10,2,5)

In [64]:
a

array([[[[101, 103, 105, 107, 109],
         [111, 113, 115, 117, 119]],

        [[121, 123, 125, 127, 129],
         [131, 133, 135, 137, 139]],

        [[141, 143, 145, 147, 149],
         [151, 153, 155, 157, 159]],

        [[161, 163, 165, 167, 169],
         [171, 173, 175, 177, 179]],

        [[181, 183, 185, 187, 189],
         [191, 193, 195, 197, 199]],

        [[201, 203, 205, 207, 209],
         [211, 213, 215, 217, 219]],

        [[221, 223, 225, 227, 229],
         [231, 233, 235, 237, 239]],

        [[241, 243, 245, 247, 249],
         [251, 253, 255, 257, 259]],

        [[261, 263, 265, 267, 269],
         [271, 273, 275, 277, 279]],

        [[281, 283, 285, 287, 289],
         [291, 293, 295, 297, 299]]]])

In [49]:
a[0][9][0][1:3]

array([91, 92])